apiVersion: v1
kind: Service
metadata:
  name: wine-store-service
  labels:
    app: wine-store
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: http-server
  selector:
    app: wine-store
